# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Critical for SPA routing - this handles client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Optional: If you have API functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200